name: Build Container
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build_container.yaml"
      - "app/**"
      - "makefile"

env:
  AWS_REGION: "eu-west-1"
  OIDC_ROLE: arn:aws:iam::675385716628:role/GithubActionsToAssume

permissions:
  id-token: write
  contents: read

jobs:
  BuildPipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{env.OIDC_ROLE}}
          aws-region: ${{env.AWS_REGION}}

      - name: Get cfn stack outputs and set in Github env
        run: |
          make outputs

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: "true"

      - name: Build, tag, and push image to Amazon ECR
        working-directory: ./app
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${{ env.ECRRepositoryUri }}:$IMAGE_TAG .
          docker tag ${{ env.ECRRepositoryUri }}:$IMAGE_TAG ${{ env.ECRRepositoryUri }}:latest 
          docker push ${{ env.ECRRepositoryUri }}:$IMAGE_TAG
          docker push ${{ env.ECRRepositoryUri }}:latest
