name: Build Container
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build_container.yaml"
      - "app/**"

env:
  AWS_REGION: "eu-west-1"
  OIDC_ROLE: arn:aws:iam::675385716628:role/GithubActionsToAssume

permissions:
  id-token: write
  contents: read

jobs:
  BuildPipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{env.OIDC_ROLE}}
          aws-region: ${{env.AWS_REGION}}

      - name: Get Stack Outputs
        working-directory: ./infra
        run: |
          make outputs
          echo "Environment variables after setting:"
          env | grep ECR

      - name: Build, tag, and push image to Amazon ECR
        working-directory: ./app
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Available environment variables:"  # Debug: show available vars
          env | grep ECR
          REPO_NAME=${ECRRepositoryName}
          echo "Repository name: $REPO_NAME"  # Debug: show repo name

          docker build -t $ECR_REGISTRY/$REPO_NAME:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$REPO_NAME:$IMAGE_TAG $ECR_REGISTRY/$REPO_NAME:latest 
          docker push $ECR_REGISTRY/$REPO_NAME:$IMAGE_TAG
          docker push $ECR_REGISTRY/$REPO_NAME:latest
